### ISSUE TITLE
Invalid video identifier?

### ISSUE THREAD

**Issue by SoneeJohn** [lilfaf/YTVimeoExtractor#20]
I get this error when trying to download this valid Vimeo video:
https://vimeo.com/75372619

Please help

**Comment by lilfaf** [comment]
This is the actual response from Vimeo. You need to tweak the security settings if that's your own video.

```json
{
    message: "Because of its privacy settings, this video cannot be played here.",
    title: "Sorry",
    button: {
        text: "Watch on Vimeo",
        link: "https://vimeo.com/75372619"
    },
    view: 7
}
````
