### ISSUE TITLE
Terms & Agreement compliant

### ISSUE THREAD

**Issue by chamroeunbm** [lilfaf/YTVimeoExtractor#21]
Hi,
It's very nice to be able to play vimeo with this.

BUT I have 1 big question. Does this code comply with ToS of Vimeo?

Will using this code cause my app to be blocked?

Regards;

**Comment by lilfaf** [comment]
Hello @chamroeunbm,
I just walked through Vimeo ToS and I can't find anything against this library. I'm not entirely sure but I guess you can use it without risk of rejects.
Best regards
