### ISSUE TITLE
"Unsupported audio codec" error, despite MP4 being available

### ISSUE THREAD

**Issue by johnrogers** [lilfaf/YTVimeoExtractor#24]
When attempting to load a video by URL or ID (for the same video), I keep getting the error 'Unsupported audio codec'. It looks like it's because it can't find the path "request.files.h264" in the JSON data.

Upon inspection of the JSON data, there's actually MP4 content in there, however it's under the "request.files.progressive" key - in there are is the MP4 content for each quality.

I'm not sure if Vimeo have changed their API responses but I don't seem to be able to find any video with the "request.files.h264" anymore, unless I'm just having bad luck.

**Comment by valdistt** [comment]
I have the same problem - "Unsupported video codec" (not audio, but we can find this text in code). It looks like, that Vimeo has changed their API, but probably there is some workaround? As our app is on the App Store and we have a serious presentation today, it really makes us serious problems now...
Any idea how to solve this?

**Comment by Chris59160** [comment]
Yes guys, Vimeo has changed their API, so now, in "- (void)connectionDidFinishLoading:(NSURLConnection *)connection"

NSDictionary *filesInfo = [jsonData valueForKeyPath:@"request.files.h264"]; will always fail, the new path is : files.hls.progressive which gives you an array of dictionary, and you need to access url in one of the 3 dictionnary depending on the quality you asked for.
They even removed sd, hd and can't remember the last quality available, and replaced by quality+ 70p or 360p or 720p.

Replace the function I mention with that one :

- (void)connectionDidFinishLoading:(NSURLConnection *)connection
{
    NSError *error;
    NSDictionary *jsonData = [NSJSONSerialization JSONObjectWithData:self.buffer options:NSJSONReadingAllowFragments error:&error];

    if (error) {
        [self extractorFailedWithMessage:@"Invalid video indentifier" errorCode:YTVimeoExtractorErrorInvalidIdentifier];
        return;
    }
    
    NSLog(@"jsonData : %@", jsonData);

    NSArray* videoArray = [jsonData valueForKeyPath:@"request.files.progressive"];
    if (!videoArray) {
        [self extractorFailedWithMessage:@"Unsupported video codec" errorCode:YTVimeoExtractorErrorUnsupportedCodec];
        return;
    }
    
    NSDictionary* videoInfos;

    switch (self.quality)
    {
        case YTVimeoVideoQualityLow:
            if (videoArray.count > 0)
            {
                videoInfos = [videoArray objectAtIndex:0];
            }
            break;
        case YTVimeoVideoQualityMedium:
            if (videoArray.count > 1)
            {
                videoInfos = [videoArray objectAtIndex:1];
            }
            break;
        default:
            if (videoArray.count > 2)
            {
                videoInfos = [videoArray objectAtIndex:2];
            }
            break;
    }
    
    if (videoInfos)
    {
        NSURL *fileURL = [NSURL URLWithString:[videoInfos objectForKey:@"url"]];
        if (self.completionHandler)
        {
            self.completionHandler(fileURL, nil, self.quality);
        }
        else if ([self.delegate respondsToSelector:@selector(vimeoExtractor:didSuccessfullyExtractVimeoURL:withQuality:)])
        {
            [self.delegate vimeoExtractor:self didSuccessfullyExtractVimeoURL:fileURL withQuality:self.quality];
        }
    }
    else
    {
        [self extractorFailedWithMessage:@"Unavailable video quality" errorCode:YTVimeoExtractorErrorUnavailableQuality];
    }

    _running = NO;
}

It does the trick for me. If The author of YTVimeoExtractor could update with the fix, for ther others to use, would be cool :-).
By the way I created an android version of it

**Comment by johnrogers** [comment]
I've submitted a pull request for this. Thanks for your input, @Chris59160.

**Comment by Chris59160** [comment]
No worries ^_^

I will check out your cleaning :-)

**Comment by eliasbagley** [comment]
Any chance we could get one of those pull requests merged in and push another release?

**Comment by jvanderwee** [comment]
+1

**Comment by lilfaf** [comment]
@eliasbagley @jvanderwee Long time waiting sorry. It's all good now ! I just released version 0.3.0. :wink:
