### ISSUE TITLE
Unsupported video codec

### ISSUE THREAD

**Issue by Nisha-SpaceoTech** [lilfaf/YTVimeoExtractor#26]
Hello,

Demo code is not working and it gives "Error Domain=YTVimeoExtractorErrorDomain Code=2 "Unsupported video codec" " error. Can you please look into this?

Thanks.

**Comment by lilfaf** [comment]
Hi @Nisha-SpaceoTech,
If your are using the master branch or the latest release then it's related to issues #24 #25.
Regards

**Comment by Nisha-SpaceoTech** [comment]
yes got it.

Thanks
