### ISSUE TITLE
Add Support for 'Private Videos'

### ISSUE THREAD

**Issue by SoneeJohn** [lilfaf/YTVimeoExtractor#30]
Currently, the library cannot download videos with certain privacy settings. For, example this video: https://vimeo.com/75372619 will bring up a Invalid video identifier error. However, the [youtube-dl](https://github.com/rg3/youtube-dl) project is able to download it. It would be great to use some of the logic from the [Vimeo Extractor Module](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/vimeo.py) and bring it to this project.

**Comment by lilfaf** [comment]
@SoneeJohn Thank again for your contribution. This was surprisingly easy to fix thanks to your links ! it seems that vimeo expects the `referer` to be their own domain for some videos.

**Comment by SoneeJohn** [comment]
@lilfaf I didn't know it would have been fixed so quickly. Thanks a lot :) :+1:

**Comment by SnehaDudhat** [comment]
@lilfaf can you elaborate , how I can play private video by referer?
Thanks in advance
