### ISSUE TITLE
Using config file may result in account removal.

### ISSUE THREAD

**Issue by marcotolman** [lilfaf/YTVimeoExtractor#32]
Hi!
Sorry for this unconventional way of communicating, ideally I'd like to send a direct message.

After Vimeo changed the response which broke the functionality we reached out to them to see if we could have been warned. In our question we mentioned the config endpoint (https://player.vimeo.com/video/%@/config) 

This is (part of) Vimeo's response:
*The Player config file is for Vimeo use only. Third-party usage of the Player config file is not supported, and continued usage of the config file may result in account removal from Vimeo per our Terms of Service: https://vimeo.com/terms
PRO users are able to access the video files for videos on their account by using the Vimeo API. More information about the API can be found here: https://developer.vimeo.com/api/start*

Any thoughts about this?

Marco

**Comment by lilfaf** [comment]
Hi @marcotolman,
This lib goes against Vimeo's terms of service. We added a notice at the bottom of the README. Use it at your own risk. Regards
