### ISSUE TITLE
Extractor Returns Unsuitable URLs

### ISSUE THREAD

**Issue by SoneeJohn** [lilfaf/YTVimeoExtractor#33]
Using the Sample app, input the following url: https://vimeo.com/1373038 and set the quality to 'Best'. And click the 'Play' button. This happens:
![screen shot 2015-12-02 at 7 53 07 am](https://cloud.githubusercontent.com/assets/4827301/11530287/c13974a6-98c9-11e5-9d52-4dfc2a46d470.png)
What happens is the extractor does not take into account that some URLs may not be playable by iOS or OS X natively. Sometimes, the url may be a Flash video.

**Comment by SoneeJohn** [comment]
I fixed it with this commit: 8ff8242. However, I don't intend for it to be merged with the master branch as yet. I'm working on other things ;) This issue was simply created as a reference point for now.

**Comment by lilfaf** [comment]
Hi @SoneeJohn,
Indeed vimeo sometime returns an unplayable stream URL. I quickly reviewed what you are doing in your various branches and it looks awsome, specially the test suite - exactly what we needed for version 1.0.0.
I'll fully review your pull request as soon as i'll have some free time.
Thank you for your great work ! Regards

**Comment by SoneeJohn** [comment]
@lilfaf Thank you very much. It's a pleasure to help.

**Comment by SoneeJohn** [comment]
@lilfaf I just opened a [pull request](https://github.com/lilfaf/YTVimeoExtractor/pull/34) now :)
