### ISSUE TITLE
Crash when a given low quality is not available

### ISSUE THREAD

**Issue by OlivierVoyer** [lilfaf/YTVimeoExtractor#35]
Hi,

Let say I want to get the lowest possible quality (YTVimeoVideoQualityLow270) but the video has only higher qualities available.

The following code is crashing because --YTVimeoVideoQualityLow270 is returning a huge unsigned integer and so videoQuality >= YTVimeoVideoQualityLow270 stays true.

            // get video info for the requested quality or fallback to the next available quality
            do {
                for (NSDictionary *info in filesInfo) {
                    if ([info[@"quality"] isEqualToString:availableVideoQualities[videoQuality]]) videoInfo = info;
                }
                if (videoInfo) break;
                videoQuality--;
            } while (!videoInfo && videoQuality >= YTVimeoVideoQualityLow270);

Suggestions:

1) Convert YTVimeoVideoQuality enum to NSInteger instead of NSUInteger to make sure --0 < 0
2) Add a YTVimeoVideoQualityLowestAvailable enum value that would act like YTVimeoVideoQualityBestAvailable but reverse

        if (self.quality == YTVimeoVideoQualityLowestAvailable) {
             videoInfo = [filesInfo firstObject];
        }

Regards

Olivier

**Comment by lilfaf** [comment]
Hi @OlivierVoyer. The ability to fallback to the next available quality has been removed in the 1.0.0 realease. You now have to handle the quality selection on your own. Please check the readme for an exemple. Best regards.
