### ISSUE TITLE
Installing via Podfile gives version 1.0.0

### ISSUE THREAD

**Issue by cannyboy** [lilfaf/YTVimeoExtractor#43]
`pod 'YTVimeoExtractor'` in a Podfile will install version 1.0.0, not the current version.

I noticed that the `pod spec` refers to 1.1.0, while the latest release is 1.2.0, so I'm not sure what is going on.

**Comment by SoneeJohn** [comment]
@cannyboy use `pod 'YTVimeoExtractor', :git => 'https://github.com/lilfaf/YTVimeoExtractor', :commit => '44103fb06a102c7376ccd593b427f21154c8643d'` until I can get the issue sorted out. 😊

**Comment by iOS-altima** [comment]
Did you forget about this problem?

**Comment by SoneeJohn** [comment]
@iOS-altima I am sorry. I'll ping @lilfaf since he can fix it.

**Comment by lilfaf** [comment]
@iOS-altima sorry for the giant delay. I just released v1.2.0 on Cocoapods. @SoneeJohn I've added you as pod contributor so that you can update the pod trunk 😉. Regards

**Comment by iOS-altima** [comment]
Thank you. But "pod 'YTVimeoExtractor'" command still installs version 1.0.0. Could you correct this?

**Comment by SoneeJohn** [comment]
@iOS-altima the pod spec seems to be been updated: https://github.com/CocoaPods/Specs/blob/master/Specs/5/6/4/YTVimeoExtractor/1.2.0/YTVimeoExtractor.podspec.json

try running `pod update YTVimeoExtractor`

**Comment by iOS-altima** [comment]
Thank you, you are right! :)
