### ISSUE TITLE
It works really nice , but i have a strange issue does the playable link gets expires after a day . Cause the app fetches the playable link plays great! I minimise the app after a day if i open and try to play through that stored url , It doesnt work , This Url no more works  

### ISSUE THREAD

**Issue by SachinB17** [lilfaf/YTVimeoExtractor#44]
It works really nice , but i have a strange issue does the playable link gets expires after a day . Cause the app fetches the playable link plays great! I minimise the app after a day if i open and try to play through that stored url , It doesnt work , This Url no more works

**Comment by SoneeJohn** [comment]
@SachinB17 yes that is correct the URL will expire after sometime.
