### ISSUE TITLE
No shared iOS scheme for Carthage

### ISSUE THREAD

**Issue by birneamstiel** [lilfaf/YTVimeoExtractor#46]
I'm trying to include YTVimeoExtractor via Carthage in my iOS project but it won't work since the only platform is Mac. Not sure if I'm missing something out here though...

**Comment by SoneeJohn** [comment]
@birneamstiel there isn't a iOS framework target, my bad. I will fix this in the future however, in the mean time it's best to use CocoaPods.

**Comment by SoneeJohn** [comment]
#47

**Comment by SoneeJohn** [comment]
@birneamstiel everything should work fine now. 🙂
